package accgf

const COOKIE_MAX_AGE = "GOAPP_ENV_COOKIE_MAX_AGE"
const COOKIE_MAX_AGE_TIMEOUT = "GOAPP_ENV_COOKIE_MAX_AGE_TIMEOUT"
const COOKIE_DOMAIN = "GOAPP_ENV_COOKIE_DOMAIN"
const COOKIE_PATH = "GOAPP_ENV_COOKIE_PATH"
const COOKIE_SECURE = "GOAPP_ENV_COOKIE_SECURE"
const COOKIE_HTTPONLY = "GOAPP_ENV_COOKIE_HTTPONLY"
const COOKIE_SAME_SITE = "GOAPP_ENV_COOKIE_SAME_SITE"
const COOKIE_CONFIG_AUTH_PARAMS = "GOAPP_ENV_COOKIE_CONFIG_AUTH_PARAMS"
const COOKIE_CONFIG_SERVER_CACHE = "GOAPP_ENV_COOKIE_CONFIG_SERVER_CACHE"
const COOKIE_CONFIG_NEW_PASSWORD = "GOAPP_ENV_COOKIE_CONFIG_NEW_PASSWORD"
const COOKIE_CONFIG_SHOP_ID = "GOAPP_ENV_COOKIE_CONFIG_SHOP_ID"
const COOKIE_CLIENT_WINDOW_NEW_PASSWORD = "GOAPP_ENV_COOKIE_CLIENT_WINDOW_NEW_PASSWORD"
